version: '3.8'

services:
  flask:
    image: flask:Aplicativo-web-1
    build: .
    volumes:
      - ./flask:/flask
    environment:
       TZ: America/Fortaleza
    restart: always
    ports:
      - "4005:80"